### ISSUE TITLE
Unable to open vgstation13's dme file - non-constant function call: alist

### ISSUE THREAD

**Issue by Eneocho** [SpaiR/StrongDMM#375]
### Version

Works as late as 2.11, fails afterwards.

### What happened?

<img width="658" height="123" alt="Image" src="https://github.com/user-attachments/assets/85aa3d66-16de-4305-8ab8-463abf363d59" />

<img width="613" height="117" alt="Image" src="https://github.com/user-attachments/assets/920a8429-b5fe-4c11-a266-d702969f6a7b" />

See pic related. the offending lines: https://github.com/vgstation-coders/vgstation13/blob/25eb7723c7a957a99324c2db688b5228a60c5480/code/modules/client/preferences/preferences.dm#L128-L130

### Reproduction

1. Run latest StrongDMM.
2. Open vgstation's latest DME.
3. Get the "non-constant function call: alist" error.
4. Download older SDMM version (2.10.0.alpha). (Other mappers have reported it working on 2.11).
5. Open vgstation's latest DME.
6. Works fine, can map unimpeded.

### Relevant log output

```bash
2025-10-26 16:52:21 DBG sdmm/internal/app/project.go:112 > opening environment [D:\Archival\vgstation13\vgstation13.dme]...
2025-10-26 16:52:21 DBG sdmm/internal/app/ui/dialog/dialog.go:50 > opening dialog:Loading
2025-10-26 16:52:21 DBG sdmm/internal/app/project.go:142 > parsing environment: [D:\Archival\vgstation13\vgstation13.dme]...
2025-10-26 16:52:21 DBG sdmm/internal/app/ui/cpwsarea/wsarea.go:356 > switch focused workspace:<nil>
2025-10-26 16:53:13 DBG sdmm/internal/app/project.go:147 > unable to open environment by path:D:\Archival\vgstation13\vgstation13.dmeparser error: compilation errors
  code/modules/client/preferences/preferences.dm - [129:39] | non-constant function call: alist
  code/modules/client/preferences/preferences.dm - [130:42] | non-constant function call: alist
2025-10-26 16:53:13 DBG sdmm/internal/app/ui/dialog/dialog.go:50 > opening dialog:Parser Error!
2025-10-26 16:53:13 DBG sdmm/internal/app/ui/dialog/dialog.go:56 > closing dialog:Loading
2025-10-26 16:53:13 DBG sdmm/internal/app/ui/dialog/dialog.go:59 > dialog closed:Loading
```

**Comment by Eneocho** [comment]
excellent
thanks, mate
